"""Build the PDF report."""

from __future__ import annotations

from datetime import date
from pathlib import Path

import geopandas as gpd
import numpy as np
import pandas as pd
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.platypus import Image, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from shapely.geometry.base import BaseGeometry

from pilot import config
from pilot.explain import rationale
from pilot.features import CoverageResult
from pilot.maps import heatmap_path, render

METHODOLOGY_SUMMARY = (
    "This report was produced by a machine-learning prospectivity model trained on "
    "public geoscientific datasets for Nevada, including USGS deposit records, "
    "NURE-HSSR stream-sediment geochemistry, USGS gravity, the State Geologic Map, "
    "NBMG hot-spring chemistry, and SRTM elevation. Predictions are generated over "
    "a uniform grid and validated with spatial cross-validation. This is a "
    "regional prospectivity assessment intended for early-stage target generation."
)

LIMITATIONS_TEXT = (
    "This assessment identifies regional geological prospectivity and is intended "
    "for early-stage target generation, not drill-site selection. It is scoped to "
    "brine-type and clay-hosted lithium systems characteristic of Nevada and does "
    "not incorporate proprietary drilling, detailed geophysical surveys, or remote "
    "sensing. Stream-sediment geochemical signals carry spatial uncertainty, as the "
    "lithium source may lie upstream of the sample point. Predictions for areas "
    "with sparse public-data coverage are lower confidence and are flagged where "
    "applicable. This analysis does not constitute a mineral resource estimate or "
    "investment advice."
)

REPORT_STATUS_TEXT = (
    "This report was generated by a preliminary test model under active development "
    "and is not produced by the final production model. The predictions presented here "
    "are for evaluation and demonstration purposes only and must not be used for "
    "investment or drilling decisions.",
    "The current model uses only publicly available geoscientific datasets. "
    "A future version of this service will allow you to supply your own proprietary data, "
    "such as gravity surveys, geochemistry, or magnetic surveys, for your area of interest. "
    "That client-supplied data will be used to refine and sharpen the input features the "
    "fixed model runs on for your ground, producing predictions tailored to your area.",
)

REPORT_FILENAME = "prospectivity_report.pdf"

SECTION_REPORT_STATUS = "Report status and scope"
SECTION_METHODOLOGY = "Methodology"
SECTION_HEATMAP = "Prospectivity heatmap"
SECTION_RANKED_TARGETS = "Ranked targets"
SECTION_TARGET_RATIONALES = "Target rationales"
SECTION_LIMITATIONS = "Limitations"
COVERAGE_HEADING = "Coverage limitation"


def report_path(client: str) -> Path:
    """Return the deterministic PDF report path for a client."""
    return heatmap_path(client).parent / REPORT_FILENAME


def build(
    *,
    features_df: pd.DataFrame,
    probabilities: np.ndarray,
    client: str,
    aoi_polygon: BaseGeometry,
    coverage: CoverageResult,
    report_date: date,
) -> Path:
    """Assemble the pilot PDF report and write it under ``outputs/<client>/``.

    Renders the heatmap via :mod:`pilot.maps` and per-target rationales via
    :mod:`pilot.explain`. Uses :data:`pilot.config.TOP_N` for the ranked table
    and rationale count.

    Args:
        features_df: Grid cells with model feature columns, ``cell_id``, and
            centroid ``geometry``.
        probabilities: One probability per row aligned with ``features_df``.
        client: Client name for the cover page and output folder.
        aoi_polygon: AOI boundary in the grid CRS (EPSG:3857).
        coverage: AOI coverage assessment from :mod:`pilot.features`.
        report_date: Date printed on the cover page (caller controls determinism).

    Returns:
        Path to the written PDF beside the heatmap PNG.

    Raises:
        ValueError: If ``probabilities`` length disagrees with ``features_df``,
            or ``client`` is empty.
    """
    if not str(client).strip():
        raise ValueError("client name must not be empty")

    n_rows = len(features_df)
    if len(probabilities) != n_rows:
        raise ValueError(
            f"probabilities length ({len(probabilities)}) does not match "
            f"features_df rows ({n_rows})"
        )

    output_path = report_path(client)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    plot_df = features_df.copy()
    plot_df["probability"] = probabilities

    heatmap_file = render(plot_df, client, aoi_polygon)
    top_targets = _top_targets_table(plot_df, probabilities)
    target_rationales = _target_rationales(plot_df, probabilities)

    _write_pdf(
        output_path=output_path,
        client=client,
        report_date=report_date,
        coverage=coverage,
        heatmap_file=heatmap_file,
        top_targets=top_targets,
        target_rationales=target_rationales,
    )
    return output_path


def _top_targets_table(
    features_df: pd.DataFrame,
    probabilities: np.ndarray,
) -> list[dict[str, object]]:
    if features_df.empty:
        return []

    ranked = features_df.copy()
    ranked["probability"] = probabilities
    ranked = ranked.sort_values("probability", ascending=False).head(config.TOP_N)

    gdf = gpd.GeoDataFrame(
        ranked,
        geometry="geometry",
        crs=config.GRID_CRS,
    ).to_crs("EPSG:4326")

    rows: list[dict[str, object]] = []
    for rank, row in enumerate(gdf.itertuples(index=False), start=1):
        rows.append(
            {
                "rank": rank,
                "cell_id": str(row.cell_id),
                "latitude": float(row.geometry.y),
                "longitude": float(row.geometry.x),
                "probability": float(row.probability),
                "dominant_lith": str(row.dominant_lith),
            }
        )
    return rows


def _target_rationales(
    features_df: pd.DataFrame,
    probabilities: np.ndarray,
) -> list[tuple[str, str]]:
    if features_df.empty:
        return []

    rationales = rationale(features_df, probabilities, top_n=config.TOP_N)
    order = [row["cell_id"] for row in _top_targets_table(features_df, probabilities)]
    return [(cell_id, rationales[str(cell_id)]) for cell_id in order]


def _write_pdf(
    *,
    output_path: Path,
    client: str,
    report_date: date,
    coverage: CoverageResult,
    heatmap_file: Path,
    top_targets: list[dict[str, object]],
    target_rationales: list[tuple[str, str]],
) -> None:
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        spaceAfter=12,
    )
    heading_style = ParagraphStyle(
        "ReportHeading",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=14,
        leading=18,
        spaceBefore=12,
        spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "ReportBody",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=11,
        leading=14,
        spaceAfter=8,
    )
    warning_style = ParagraphStyle(
        "CoverageWarning",
        parent=body_style,
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=15,
        textColor=colors.HexColor("#8B0000"),
        spaceAfter=10,
    )

    story: list[object] = [
        Paragraph(client.strip(), title_style),
        Paragraph(f"Date: {report_date.isoformat()}", body_style),
        Spacer(1, 0.2 * inch),
    ]

    if not coverage.adequate:
        minimum_pct = config.COVERAGE_MIN_FRACTION * 100
        covered_pct = coverage.fraction * 100
        story.extend(
            [
                Paragraph(COVERAGE_HEADING, heading_style),
                Paragraph(
                    (
                        f"Only {covered_pct:.1f}% of this area of interest is covered by the "
                        f"precomputed Nevada feature grid (minimum required: {minimum_pct:.0f}%). "
                        "Predictions and ranked targets for uncovered ground are not reliable "
                        "and must not be used where the grid has no coverage."
                    ),
                    warning_style,
                ),
                Spacer(1, 0.15 * inch),
            ]
        )

    story.extend(
        [
            Paragraph(SECTION_REPORT_STATUS, heading_style),
            Paragraph(REPORT_STATUS_TEXT[0], body_style),
            Paragraph(REPORT_STATUS_TEXT[1], body_style),
            Paragraph(SECTION_METHODOLOGY, heading_style),
            Paragraph(METHODOLOGY_SUMMARY, body_style),
            Paragraph(SECTION_HEATMAP, heading_style),
        ]
    )

    image = Image(str(heatmap_file))
    image.drawWidth = 6.5 * inch
    image.drawHeight = 4.5 * inch
    story.extend([image, Spacer(1, 0.15 * inch)])

    story.append(Paragraph(SECTION_RANKED_TARGETS, heading_style))
    if top_targets:
        table_data = [
            [
                "Rank",
                "Latitude",
                "Longitude",
                "Probability",
                "Dominant lithology",
            ]
        ]
        for row in top_targets:
            table_data.append(
                [
                    str(row["rank"]),
                    f"{row['latitude']:.6f}",
                    f"{row['longitude']:.6f}",
                    f"{row['probability']:.6f}",
                    str(row["dominant_lith"]),
                ]
            )
        table = Table(
            table_data,
            colWidths=[0.6 * inch, 1.1 * inch, 1.1 * inch, 1.0 * inch, 2.2 * inch],
        )
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E8E8E8")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ]
            )
        )
        story.extend([table, Spacer(1, 0.15 * inch)])
    else:
        story.append(Paragraph("No ranked targets are available for this AOI.", body_style))

    story.append(Paragraph(SECTION_TARGET_RATIONALES, heading_style))
    if target_rationales:
        for rank, (cell_id, rationale_text) in enumerate(target_rationales, start=1):
            story.append(
                Paragraph(
                    f"<b>Target {rank} ({cell_id})</b><br/>{rationale_text}",
                    body_style,
                )
            )
    else:
        story.append(Paragraph("No target rationales are available for this AOI.", body_style))

    story.extend(
        [
            Paragraph(SECTION_LIMITATIONS, heading_style),
            Paragraph(LIMITATIONS_TEXT, body_style),
        ]
    )

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=letter,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        title=f"Lithium prospectivity report — {client.strip()}",
        author="Pilot MVP pipeline",
        canvasmaker=_invariant_canvas,
    )
    doc.build(story)
    _set_fixed_pdf_dates(output_path)


def _invariant_canvas(filename: str, **kwargs: object) -> canvas.Canvas:
    report_canvas = canvas.Canvas(filename, invariant=1, **kwargs)
    report_canvas.setPageCompression(0)
    return report_canvas


def _set_fixed_pdf_dates(output_path: Path) -> None:
    """Normalize PDF trailer dates so repeated builds are byte-identical."""
    fixed = b"D:20260101000000"
    data = bytearray(output_path.read_bytes())
    for token in (b"/CreationDate ", b"/ModDate "):
        start = 0
        while True:
            idx = data.find(token, start)
            if idx < 0:
                break
            open_paren = data.find(b"(", idx)
            close_paren = data.find(b")", open_paren + 1)
            if open_paren < 0 or close_paren < 0:
                break
            data[open_paren + 1 : close_paren] = fixed
            start = close_paren + 1
    output_path.write_bytes(data)
